version: "3.9"

networks:
  mynetwork:

services:
  postgres:
    image: alexbartenev/postgres:latest
    env_file:
      - ../.env
    volumes:
      - ./imports/postgres/init/test_dump.sql:/docker-entrypoint-initdb.d/test_dump.sql
    build:
      context: ../../testcontainers2024/docker/imports/postgres
      dockerfile: /docker/imports/postgres/Dockerfile
    ports:
      - "32768:5432"
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  testcontainers2024:
    image: alexbartenev/testcontainers2024:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users
    build:
      context: ../../testcontainers2024
      dockerfile: ../testcontainers2024/Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    depends_on:
      - postgres